'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(""),  _
         Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
        Public Property CheckBox01_button_name() As String
            Get
                Return CType(Me("CheckBox01_button_name"),String)
            End Get
            Set
                Me("CheckBox01_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(""),  _
         Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
        Public Property CheckBox02_button_name() As String
            Get
                Return CType(Me("CheckBox02_button_name"),String)
            End Get
            Set
                Me("CheckBox02_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(""),  _
         Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
        Public Property CheckBox04_button_name() As String
            Get
                Return CType(Me("CheckBox04_button_name"),String)
            End Get
            Set
                Me("CheckBox04_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(""),  _
         Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>  _
        Public Property CheckBox05_button_name() As String
            Get
                Return CType(Me("CheckBox05_button_name"),String)
            End Get
            Set
                Me("CheckBox05_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox06_button_name() As String
            Get
                Return CType(Me("CheckBox06_button_name"),String)
            End Get
            Set
                Me("CheckBox06_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox07_button_name() As String
            Get
                Return CType(Me("CheckBox07_button_name"),String)
            End Get
            Set
                Me("CheckBox07_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox08_button_name() As String
            Get
                Return CType(Me("CheckBox08_button_name"),String)
            End Get
            Set
                Me("CheckBox08_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox09_button_name() As String
            Get
                Return CType(Me("CheckBox09_button_name"),String)
            End Get
            Set
                Me("CheckBox09_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox10_button_name() As String
            Get
                Return CType(Me("CheckBox10_button_name"),String)
            End Get
            Set
                Me("CheckBox10_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox12_button_name() As String
            Get
                Return CType(Me("CheckBox12_button_name"),String)
            End Get
            Set
                Me("CheckBox12_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox13_button_name() As String
            Get
                Return CType(Me("CheckBox13_button_name"),String)
            End Get
            Set
                Me("CheckBox13_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox14_button_name() As String
            Get
                Return CType(Me("CheckBox14_button_name"),String)
            End Get
            Set
                Me("CheckBox14_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox15_button_name() As String
            Get
                Return CType(Me("CheckBox15_button_name"),String)
            End Get
            Set
                Me("CheckBox15_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox16_button_name() As String
            Get
                Return CType(Me("CheckBox16_button_name"),String)
            End Get
            Set
                Me("CheckBox16_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox17_button_name() As String
            Get
                Return CType(Me("CheckBox17_button_name"),String)
            End Get
            Set
                Me("CheckBox17_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox18_button_name() As String
            Get
                Return CType(Me("CheckBox18_button_name"),String)
            End Get
            Set
                Me("CheckBox18_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox25_button_name() As String
            Get
                Return CType(Me("CheckBox25_button_name"),String)
            End Get
            Set
                Me("CheckBox25_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox26_button_name() As String
            Get
                Return CType(Me("CheckBox26_button_name"),String)
            End Get
            Set
                Me("CheckBox26_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox28_button_name() As String
            Get
                Return CType(Me("CheckBox28_button_name"),String)
            End Get
            Set
                Me("CheckBox28_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox29_button_name() As String
            Get
                Return CType(Me("CheckBox29_button_name"),String)
            End Get
            Set
                Me("CheckBox29_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox30_button_name() As String
            Get
                Return CType(Me("CheckBox30_button_name"),String)
            End Get
            Set
                Me("CheckBox30_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox31_button_name() As String
            Get
                Return CType(Me("CheckBox31_button_name"),String)
            End Get
            Set
                Me("CheckBox31_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox32_button_name() As String
            Get
                Return CType(Me("CheckBox32_button_name"),String)
            End Get
            Set
                Me("CheckBox32_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox33_button_name() As String
            Get
                Return CType(Me("CheckBox33_button_name"),String)
            End Get
            Set
                Me("CheckBox33_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox34_button_name() As String
            Get
                Return CType(Me("CheckBox34_button_name"),String)
            End Get
            Set
                Me("CheckBox34_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox36_button_name() As String
            Get
                Return CType(Me("CheckBox36_button_name"),String)
            End Get
            Set
                Me("CheckBox36_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox37_button_name() As String
            Get
                Return CType(Me("CheckBox37_button_name"),String)
            End Get
            Set
                Me("CheckBox37_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox38_button_name() As String
            Get
                Return CType(Me("CheckBox38_button_name"),String)
            End Get
            Set
                Me("CheckBox38_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox39_button_name() As String
            Get
                Return CType(Me("CheckBox39_button_name"),String)
            End Get
            Set
                Me("CheckBox39_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox40_button_name() As String
            Get
                Return CType(Me("CheckBox40_button_name"),String)
            End Get
            Set
                Me("CheckBox40_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox41_button_name() As String
            Get
                Return CType(Me("CheckBox41_button_name"),String)
            End Get
            Set
                Me("CheckBox41_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox42_button_name() As String
            Get
                Return CType(Me("CheckBox42_button_name"),String)
            End Get
            Set
                Me("CheckBox42_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox44_button_name() As String
            Get
                Return CType(Me("CheckBox44_button_name"),String)
            End Get
            Set
                Me("CheckBox44_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox45_button_name() As String
            Get
                Return CType(Me("CheckBox45_button_name"),String)
            End Get
            Set
                Me("CheckBox45_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox46_button_name() As String
            Get
                Return CType(Me("CheckBox46_button_name"),String)
            End Get
            Set
                Me("CheckBox46_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox47_button_name() As String
            Get
                Return CType(Me("CheckBox47_button_name"),String)
            End Get
            Set
                Me("CheckBox47_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox48_button_name() As String
            Get
                Return CType(Me("CheckBox48_button_name"),String)
            End Get
            Set
                Me("CheckBox48_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox49_button_name() As String
            Get
                Return CType(Me("CheckBox49_button_name"),String)
            End Get
            Set
                Me("CheckBox49_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox50_button_name() As String
            Get
                Return CType(Me("CheckBox50_button_name"),String)
            End Get
            Set
                Me("CheckBox50_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox52_button_name() As String
            Get
                Return CType(Me("CheckBox52_button_name"),String)
            End Get
            Set
                Me("CheckBox52_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox53_button_name() As String
            Get
                Return CType(Me("CheckBox53_button_name"),String)
            End Get
            Set
                Me("CheckBox53_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox54_button_name() As String
            Get
                Return CType(Me("CheckBox54_button_name"),String)
            End Get
            Set
                Me("CheckBox54_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox55_button_name() As String
            Get
                Return CType(Me("CheckBox55_button_name"),String)
            End Get
            Set
                Me("CheckBox55_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox56_button_name() As String
            Get
                Return CType(Me("CheckBox56_button_name"),String)
            End Get
            Set
                Me("CheckBox56_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox57_button_name() As String
            Get
                Return CType(Me("CheckBox57_button_name"),String)
            End Get
            Set
                Me("CheckBox57_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox58_button_name() As String
            Get
                Return CType(Me("CheckBox58_button_name"),String)
            End Get
            Set
                Me("CheckBox58_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox65_button_name() As String
            Get
                Return CType(Me("CheckBox65_button_name"),String)
            End Get
            Set
                Me("CheckBox65_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox66_button_name() As String
            Get
                Return CType(Me("CheckBox66_button_name"),String)
            End Get
            Set
                Me("CheckBox66_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox68_button_name() As String
            Get
                Return CType(Me("CheckBox68_button_name"),String)
            End Get
            Set
                Me("CheckBox68_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox69_button_name() As String
            Get
                Return CType(Me("CheckBox69_button_name"),String)
            End Get
            Set
                Me("CheckBox69_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox70_button_name() As String
            Get
                Return CType(Me("CheckBox70_button_name"),String)
            End Get
            Set
                Me("CheckBox70_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox71_button_name() As String
            Get
                Return CType(Me("CheckBox71_button_name"),String)
            End Get
            Set
                Me("CheckBox71_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox72_button_name() As String
            Get
                Return CType(Me("CheckBox72_button_name"),String)
            End Get
            Set
                Me("CheckBox72_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox73_button_name() As String
            Get
                Return CType(Me("CheckBox73_button_name"),String)
            End Get
            Set
                Me("CheckBox73_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox74_button_name() As String
            Get
                Return CType(Me("CheckBox74_button_name"),String)
            End Get
            Set
                Me("CheckBox74_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox76_button_name() As String
            Get
                Return CType(Me("CheckBox76_button_name"),String)
            End Get
            Set
                Me("CheckBox76_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox77_button_name() As String
            Get
                Return CType(Me("CheckBox77_button_name"),String)
            End Get
            Set
                Me("CheckBox77_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox78_button_name() As String
            Get
                Return CType(Me("CheckBox78_button_name"),String)
            End Get
            Set
                Me("CheckBox78_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox79_button_name() As String
            Get
                Return CType(Me("CheckBox79_button_name"),String)
            End Get
            Set
                Me("CheckBox79_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox80_button_name() As String
            Get
                Return CType(Me("CheckBox80_button_name"),String)
            End Get
            Set
                Me("CheckBox80_button_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox01_timeline_name() As String
            Get
                Return CType(Me("CheckBox01_timeline_name"),String)
            End Get
            Set
                Me("CheckBox01_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox02_timeline_name() As String
            Get
                Return CType(Me("CheckBox02_timeline_name"),String)
            End Get
            Set
                Me("CheckBox02_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox04_timeline_name() As String
            Get
                Return CType(Me("CheckBox04_timeline_name"),String)
            End Get
            Set
                Me("CheckBox04_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox05_timeline_name() As String
            Get
                Return CType(Me("CheckBox05_timeline_name"),String)
            End Get
            Set
                Me("CheckBox05_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox06_timeline_name() As String
            Get
                Return CType(Me("CheckBox06_timeline_name"),String)
            End Get
            Set
                Me("CheckBox06_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox07_timeline_name() As String
            Get
                Return CType(Me("CheckBox07_timeline_name"),String)
            End Get
            Set
                Me("CheckBox07_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox08_timeline_name() As String
            Get
                Return CType(Me("CheckBox08_timeline_name"),String)
            End Get
            Set
                Me("CheckBox08_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox09_timeline_name() As String
            Get
                Return CType(Me("CheckBox09_timeline_name"),String)
            End Get
            Set
                Me("CheckBox09_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox10_timeline_name() As String
            Get
                Return CType(Me("CheckBox10_timeline_name"),String)
            End Get
            Set
                Me("CheckBox10_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox12_timeline_name() As String
            Get
                Return CType(Me("CheckBox12_timeline_name"),String)
            End Get
            Set
                Me("CheckBox12_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox13_timeline_name() As String
            Get
                Return CType(Me("CheckBox13_timeline_name"),String)
            End Get
            Set
                Me("CheckBox13_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox14_timeline_name() As String
            Get
                Return CType(Me("CheckBox14_timeline_name"),String)
            End Get
            Set
                Me("CheckBox14_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox15_timeline_name() As String
            Get
                Return CType(Me("CheckBox15_timeline_name"),String)
            End Get
            Set
                Me("CheckBox15_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox16_timeline_name() As String
            Get
                Return CType(Me("CheckBox16_timeline_name"),String)
            End Get
            Set
                Me("CheckBox16_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox17_timeline_name() As String
            Get
                Return CType(Me("CheckBox17_timeline_name"),String)
            End Get
            Set
                Me("CheckBox17_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox18_timeline_name() As String
            Get
                Return CType(Me("CheckBox18_timeline_name"),String)
            End Get
            Set
                Me("CheckBox18_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox25_timeline_name() As String
            Get
                Return CType(Me("CheckBox25_timeline_name"),String)
            End Get
            Set
                Me("CheckBox25_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox26_timeline_name() As String
            Get
                Return CType(Me("CheckBox26_timeline_name"),String)
            End Get
            Set
                Me("CheckBox26_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox28_timeline_name() As String
            Get
                Return CType(Me("CheckBox28_timeline_name"),String)
            End Get
            Set
                Me("CheckBox28_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox29_timeline_name() As String
            Get
                Return CType(Me("CheckBox29_timeline_name"),String)
            End Get
            Set
                Me("CheckBox29_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox30_timeline_name() As String
            Get
                Return CType(Me("CheckBox30_timeline_name"),String)
            End Get
            Set
                Me("CheckBox30_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox31_timeline_name() As String
            Get
                Return CType(Me("CheckBox31_timeline_name"),String)
            End Get
            Set
                Me("CheckBox31_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox32_timeline_name() As String
            Get
                Return CType(Me("CheckBox32_timeline_name"),String)
            End Get
            Set
                Me("CheckBox32_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox33_timeline_name() As String
            Get
                Return CType(Me("CheckBox33_timeline_name"),String)
            End Get
            Set
                Me("CheckBox33_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox34_timeline_name() As String
            Get
                Return CType(Me("CheckBox34_timeline_name"),String)
            End Get
            Set
                Me("CheckBox34_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox36_timeline_name() As String
            Get
                Return CType(Me("CheckBox36_timeline_name"),String)
            End Get
            Set
                Me("CheckBox36_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox37_timeline_name() As String
            Get
                Return CType(Me("CheckBox37_timeline_name"),String)
            End Get
            Set
                Me("CheckBox37_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox38_timeline_name() As String
            Get
                Return CType(Me("CheckBox38_timeline_name"),String)
            End Get
            Set
                Me("CheckBox38_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox39_timeline_name() As String
            Get
                Return CType(Me("CheckBox39_timeline_name"),String)
            End Get
            Set
                Me("CheckBox39_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox40_timeline_name() As String
            Get
                Return CType(Me("CheckBox40_timeline_name"),String)
            End Get
            Set
                Me("CheckBox40_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox41_timeline_name() As String
            Get
                Return CType(Me("CheckBox41_timeline_name"),String)
            End Get
            Set
                Me("CheckBox41_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox42_timeline_name() As String
            Get
                Return CType(Me("CheckBox42_timeline_name"),String)
            End Get
            Set
                Me("CheckBox42_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox44_timeline_name() As String
            Get
                Return CType(Me("CheckBox44_timeline_name"),String)
            End Get
            Set
                Me("CheckBox44_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox45_timeline_name() As String
            Get
                Return CType(Me("CheckBox45_timeline_name"),String)
            End Get
            Set
                Me("CheckBox45_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox46_timeline_name() As String
            Get
                Return CType(Me("CheckBox46_timeline_name"),String)
            End Get
            Set
                Me("CheckBox46_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox47_timeline_name() As String
            Get
                Return CType(Me("CheckBox47_timeline_name"),String)
            End Get
            Set
                Me("CheckBox47_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox48_timeline_name() As String
            Get
                Return CType(Me("CheckBox48_timeline_name"),String)
            End Get
            Set
                Me("CheckBox48_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox49_timeline_name() As String
            Get
                Return CType(Me("CheckBox49_timeline_name"),String)
            End Get
            Set
                Me("CheckBox49_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox50_timeline_name() As String
            Get
                Return CType(Me("CheckBox50_timeline_name"),String)
            End Get
            Set
                Me("CheckBox50_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox52_timeline_name() As String
            Get
                Return CType(Me("CheckBox52_timeline_name"),String)
            End Get
            Set
                Me("CheckBox52_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox53_timeline_name() As String
            Get
                Return CType(Me("CheckBox53_timeline_name"),String)
            End Get
            Set
                Me("CheckBox53_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox54_timeline_name() As String
            Get
                Return CType(Me("CheckBox54_timeline_name"),String)
            End Get
            Set
                Me("CheckBox54_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox55_timeline_name() As String
            Get
                Return CType(Me("CheckBox55_timeline_name"),String)
            End Get
            Set
                Me("CheckBox55_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox56_timeline_name() As String
            Get
                Return CType(Me("CheckBox56_timeline_name"),String)
            End Get
            Set
                Me("CheckBox56_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox57_timeline_name() As String
            Get
                Return CType(Me("CheckBox57_timeline_name"),String)
            End Get
            Set
                Me("CheckBox57_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox58_timeline_name() As String
            Get
                Return CType(Me("CheckBox58_timeline_name"),String)
            End Get
            Set
                Me("CheckBox58_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox65_timeline_name() As String
            Get
                Return CType(Me("CheckBox65_timeline_name"),String)
            End Get
            Set
                Me("CheckBox65_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox66_timeline_name() As String
            Get
                Return CType(Me("CheckBox66_timeline_name"),String)
            End Get
            Set
                Me("CheckBox66_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox68_timeline_name() As String
            Get
                Return CType(Me("CheckBox68_timeline_name"),String)
            End Get
            Set
                Me("CheckBox68_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox69_timeline_name() As String
            Get
                Return CType(Me("CheckBox69_timeline_name"),String)
            End Get
            Set
                Me("CheckBox69_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox70_timeline_name() As String
            Get
                Return CType(Me("CheckBox70_timeline_name"),String)
            End Get
            Set
                Me("CheckBox70_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox71_timeline_name() As String
            Get
                Return CType(Me("CheckBox71_timeline_name"),String)
            End Get
            Set
                Me("CheckBox71_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox72_timeline_name() As String
            Get
                Return CType(Me("CheckBox72_timeline_name"),String)
            End Get
            Set
                Me("CheckBox72_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox73_timeline_name() As String
            Get
                Return CType(Me("CheckBox73_timeline_name"),String)
            End Get
            Set
                Me("CheckBox73_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox74_timeline_name() As String
            Get
                Return CType(Me("CheckBox74_timeline_name"),String)
            End Get
            Set
                Me("CheckBox74_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox76_timeline_name() As String
            Get
                Return CType(Me("CheckBox76_timeline_name"),String)
            End Get
            Set
                Me("CheckBox76_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox77_timeline_name() As String
            Get
                Return CType(Me("CheckBox77_timeline_name"),String)
            End Get
            Set
                Me("CheckBox77_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox78_timeline_name() As String
            Get
                Return CType(Me("CheckBox78_timeline_name"),String)
            End Get
            Set
                Me("CheckBox78_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox79_timeline_name() As String
            Get
                Return CType(Me("CheckBox79_timeline_name"),String)
            End Get
            Set
                Me("CheckBox79_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CheckBox80_timeline_name() As String
            Get
                Return CType(Me("CheckBox80_timeline_name"),String)
            End Get
            Set
                Me("CheckBox80_timeline_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Auto_load_timeline() As String
            Get
                Return CType(Me("Auto_load_timeline"),String)
            End Get
            Set
                Me("Auto_load_timeline") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Auto_prepare_timeline() As String
            Get
                Return CType(Me("Auto_prepare_timeline"),String)
            End Get
            Set
                Me("Auto_prepare_timeline") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.XK_60_S2.My.MySettings
            Get
                Return Global.XK_60_S2.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
